@startuml
start

:Админ выбирает запись в расписании;
:Вводит изменения (дата, время, аудитория, препод);

if (Пересечения?) then (Да)
    :Показать ошибку;
else (Нет)
    :Сохранить изменения;
endif

stop
@enduml
