@startuml
start

:Студент выбирает группу/дату/преподавателя;
:Система получает данные расписания;

if (Данные найдены?) then (Да)
    :Показать расписание;
else (Нет)
    :Расписание отсутствует;
endif

stop
@enduml
