@startuml
hide circle
hide methods
hide stereotypes
skinparam linetype ortho

' ===== Сущности =====

entity "Группа" as Group {
  *ID_группы
  --
  Название_группы
  Курс
}

entity "Преподаватели" as Teacher {
  *ID_преподавателя
  --
  ФИО
  Предметы_которые_ведёт
  Почта_для_связи
}

entity "Предметы" as Subject {
  *ID_предмета
  --
  Название_предмета
  Тип_занятия_(лекция_или_практика)
  Преподаватель
}

entity "Аудитория" as Room {
  *ID_аудитории
  --
  Корпус
  Аудитория
}

entity "Дата_и_время" as DateTime {
  *ID_слота
  --
  День_недели
  Номер_пары
  Тип_недели_(чётная_нечётная)
}

entity "Расписание" as Schedule {
  *ID_записи
  --
  Группа
  Преподаватель
  Предмет
  Аудитория
  Дата_и_время
  Тип_занятия
}

' ===== Связи =====
' Предмет закреплён за преподавателем
Teacher ||--o{ Subject : "ведёт"

' Расписание: каждая сущность может встречаться много раз в расписании
Group    ||--o{ Schedule : "для группы"
Teacher  ||--o{ Schedule : "ведёт"
Subject  ||--o{ Schedule : "по предмету"
Room     ||--o{ Schedule : "в аудитории"
DateTime ||--o{ Schedule : "во время"

@enduml
